Repository helibproject/HElib, pull requests merged in 2020-10, with the labels that each got.

#29 v1.1.0 Documentation update
  documentation/Design_Document/HElib-design.pdf
  documentation/Design_Document/old/HElibrary.pdf
  documentation/Design_Document/old/HElibrary.pptx
  documentation/Design_Document/old/he-library.bib
  documentation/Design_Document/old/he-library.pdf
  documentation/Design_Document/old/he-library.tex
  documentation/mainpage.dox
Labels: documentation

#33 New encoding API
  include/helib/Context.h
  include/helib/Ctxt.h
  include/helib/DoubleCRT.h
  include/helib/EncodedPtxt.h
  include/helib/EncryptedArray.h
  include/helib/NumbTh.h
  include/helib/PAlgebra.h
  include/helib/keys.h
  include/helib/matmul.h
  include/helib/permutations.h
  include/helib/replicate.h
  include/helib/zzX.h
  misc/legacy_tests/Test_CKKS_matmul.cpp
  misc/legacy_tests/tapprox1.cpp
  misc/legacy_tests/tperms1.cpp
  src/CMakeLists.txt
  src/Ctxt.cpp
  src/EaCx.cpp
  src/EncryptedArray.cpp
  src/NumbTh.cpp
  src/PAlgebra.cpp
  src/PermNetwork.cpp
  src/Ptxt.cpp
  src/debugging.cpp
  src/intraSlot.cpp
  src/keys.cpp
  src/matmul.cpp
  src/permutations.cpp
  src/primeChain.cpp
  src/replicate.cpp
  src/zzX.cpp
  tests/CMakeLists.txt
  tests/GTestApproxNums.cpp
  tests/GTestPermutations.cpp
  tests/TestCKKS.cpp
  tests/TestMatmulCKKS.cpp
  tests/TestPermutations.cpp
  tests/test_common.cpp
  tests/test_common.h
Labels: enhancement

#37 New encoding APIs - tweaks two
  examples/BGV_binary_arithmetic/BGV_binary_arithmetic.cpp
  include/helib/Context.h
  include/helib/Ctxt.h
  include/helib/EncryptedArray.h
  include/helib/NumbTh.h
  include/helib/Ptxt.h
  include/helib/keys.h
  include/helib/matmul.h
  include/helib/primeChain.h
  include/helib/recryption.h
  include/helib/replicate.h
  misc/legacy_tests/Test_Bin_IO.cpp
  misc/legacy_tests/Test_CKKS_matmul.cpp
  misc/legacy_tests/Test_General.cpp
  misc/legacy_tests/Test_IO.cpp
  misc/legacy_tests/Test_ThinBootstrapping.cpp
  misc/legacy_tests/Test_ThinEvalMap.cpp
  misc/legacy_tests/Test_binaryArith.cpp
  misc/legacy_tests/Test_binaryCompare.cpp
  misc/legacy_tests/Test_bootstrapping.cpp
  misc/legacy_tests/Test_fatboot.cpp
  misc/legacy_tests/Test_tableLookup.cpp
  misc/legacy_tests/Test_thinboot.cpp
  misc/legacy_tests/tapprox1.cpp
  misc/paramUtils/ckks-sec128.csv
  misc/paramUtils/ckks-sec80.csv
  misc/paramUtils/ckks_parameters.cpp
  src/Context.cpp
  src/Ctxt.cpp
  src/EaCx.cpp
  src/EncryptedArray.cpp
  src/NumbTh.cpp
  src/Ptxt.cpp
  src/debugging.cpp
  src/keys.cpp
  src/matmul.cpp
  src/norms.cpp
  src/primeChain.cpp
  src/recryption.cpp
  tests/GTestApproxNums.cpp
  tests/GTestBinIO.cpp
  tests/GTestBinaryArith.cpp
  tests/GTestBinaryCompare.cpp
  tests/GTestBootstrapping.cpp
  tests/GTestFatboot.cpp
  tests/GTestGeneral.cpp
  tests/GTestIO.cpp
  tests/GTestTableLookup.cpp
  tests/GTestThinBootstrapping.cpp
  tests/GTestThinEvalMap.cpp
  tests/GTestThinboot.cpp
  tests/TestBootstrappingWithMultiplications.cpp
  tests/TestCKKS.cpp
  tests/TestContext.cpp
  tests/TestMatmulCKKS.cpp
  tests/TestPtxt.cpp
  utils/create-context/create-context.cpp
Labels: enhancement

#39 Debug module initialization for TestMatrix.cpp
  tests/TestMatrix.cpp
Labels: bug
